ci: migrate ci process to Github actions
strongloop/loopback4-example-shopping pull request #998
Opened 2021-01-08 19:46 UTC by mrmodise

2021-01-09 04:02 UTC, achrinza requested changes
Great first progress on porting over to GitHub actions! Here's my initial review 👇

2021-01-09 04:02 UTC, achrinza commented on .github/workflows/continous-integration.yaml
> +        run: git fetch --prune --unshallow
We probably should also update the yaml in loopback-next too.

```suggestion
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

2021-01-09 04:05 UTC, achrinza commented
> not sure whether we need test-benchmark for this repo?

If there isn't an existing test-benchmark in the Travis CI, then I don't think we need to add one.

> also, the repetitive build steps on linting.

Hmm, you're right; I'm not too sure why we're building before linting. If we can remove it, then that'll be a plus

2021-01-09 09:20 UTC, mrmodise commented
PTAL @achrinza

2021-01-09 10:28 UTC, mrmodise commented
@achrinza cant start Mongodb on Window nor Macos. See https://github.com/mrmodise/loopback4-example-shopping/pull/3

2021-01-09 11:24 UTC, achrinza commented
This seems to be a [known limitation](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices) :(

> Note: If your workflows use Docker container actions or service containers, then you must use a Linux runner

We could consider segregating the database integration tests so that we only run it on the ubuntu runners.

2021-01-09 12:36 UTC, mrmodise commented
> This seems to be a [known limitation](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices) :(
> 
> > Note: If your workflows use Docker container actions or service containers, then you must use a Linux runner
> 
> We could consider segregating the database integration tests so that we only run it on the ubuntu runners.

Ya let me remove the other OS and then create another PR for this

2021-01-09 12:47 UTC, mrmodise commented
Found a work-around for Windows 😄

2021-01-09 14:52 UTC, mrmodise commented
All green including Windows and MacOs although targeting node 15 only on these:

<img width="923" alt="Screenshot at Jan 09 16-50-18" src="https://user-images.githubusercontent.com/5213555/104094654-dceea280-529a-11eb-892e-6e687fcab967.png">


https://github.com/mrmodise/loopback4-example-shopping/pull/3#issuecomment-757272178

2021-01-09 16:34 UTC, achrinza commented
Add my comment here:

https://github.com/mrmodise/loopback4-example-shopping/pull/3#discussion_r554445442

2021-01-09 16:46 UTC, achrinza approved these changes
Overall, LGTM.

Minor nitpick (feel free to ignore):

The arrangement of the OS-specific steps for MongoDB and Redis aren't consistent. So perhaps we could swap the Redis Windows and macOS steps to make it easier to read.

![image](https://user-images.githubusercontent.com/25147899/104103441-18aa5c00-52dd-11eb-8114-3291086b1437.jpeg)

2021-01-09 16:51 UTC, mrmodise commented
@achrinza i grouped them thanks

2021-01-09 16:52 UTC, achrinza approved these changes
👍

2021-01-10 03:19 UTC, raymondfeng commented
@mrmodise Great work. I wonder why this PR does not trigger the github actions.

2021-01-10 03:24 UTC, mrmodise commented
@raymondfeng same here but i suspect its some setting on the repo cause i tested on my forked version and it triggered the pipeline: https://github.com/mrmodise/loopback4-example-shopping/pull/3

2021-01-10 03:28 UTC, merged

2021-01-11 12:24 UTC, bajtos commented
This is awesome, thank you @mrmodise for the contribution! ❤️